export default {
  cheap: { title: 'Cheap', emoji: '🤑' },
  moderate: { title: 'Moderate', emoji: '💰' },
  expensive: { title: 'Expensive', emoji: '💸' },
  indoor: { title: 'Indoor', emoji: '🏬' },
  outdoor: { title: 'Outdoor', emoji: '☀️' },
  sightSee: { title: 'Sight See', emoji: '👀' },
  liveMusic: { title: 'Live Music', emoji: '🎸' },
  dance: { title: 'Dance', emoji: '💃' },
  drink: { title: 'Drink', emoji: '🍻' },
  relax: { title: 'Relax', emoji: '🛀' },
  nature: { title: 'Nature', emoji: '🌴' },
  sports: { title: 'Sports', emoji: '🏟' },
  comedy: { title: 'Comedy', emoji: '🤣' },
  adult: { title: 'Adult', emoji: '🙈' },
  museum: { title: 'Museum', emoji: '🖼' },
  park: { title: 'Park', emoji: '🏞' },
  gambling: { title: 'Gambling', emoji: '🃏' },
  art: { title: 'Art', emoji: '🎨' },
  videoGames: { title: 'Video Games', emoji: '🎮' },
};
